package mxhx.internal.parser.hxparse;

/**
	Represents a state in the state machine generated by the `LexEngine`.
**/
@:dox(hide)
class State {
	/**
		The transition vector, where the index corresponds to a char code.
	**/
	public var trans:haxe.ds.Vector<State>;

	/**
		The ids of the final states.
	**/
	public var finalId:Int;

	/**
		Creates a new State.
	**/
	public function new() {
		finalId = -1;
		trans = new haxe.ds.Vector(256);
	}
}
